apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.stack.name }}-secret-store
  namespace: argocd
spec:
  project: {{ .Values.stack.name }}
  source:
    repoURL: '{{ .Values.source.repoURL }}'
    targetRevision: '{{ .Values.source.targetRevision }}'
    path: manifests/secret-store
    helm:
      valuesObject:
        stack:
          name: '{{ .Values.stack.name }}'
        secrets:
          backend:
            kubernetes:
              namespace: '{{ .Values.secrets.backend.kubernetes.namespace | default (printf "%s-secrets" .Values.stack.name) }}'
            infisical:
              endpoint: '{{ .Values.secrets.backend.infisical.endpoint }}'
              projectSlug: '{{ .Values.secrets.backend.infisical.projectSlug }}'
              environment: '{{ .Values.secrets.backend.infisical.environment }}'
              secretsPath: '{{ .Values.secrets.backend.infisical.secretsPath }}'
              credentialsSecret: '{{ .Values.secrets.backend.infisical.credentialsSecret }}'
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets
  syncPolicy:
    {{- if .Values.autosync.enabled }}
    automated:
      prune: true
    {{- end }}
    syncOptions:
      - CreateNamespace=true
