stack:
  name: appstack  # Must match the stack name set during bootstrap

secrets:
  backend:
    kubernetes:
      namespace: "" # defaults to {{ stack.name }}-secrets
    infisical:
      endpoint: https://eu.infisical.com
      projectSlug: ""
      environment: dev
      secretsPath: ""
