stack:
  name: appstack

autosync:
  enabled: false

cluster:
  domain: appstack.local

source:
  repoURL: https://github.com/your-org/your-repo.git
  targetRevision: HEAD

secrets:
  backend:
    kubernetes:
      namespace: "" # defaults to {{ stack.name }}-secrets
    infisical:
      endpoint: ""
      environment: ""
      projectSlug: ""
      secretsPath: ""

oauth:
  enabled: false
  authUrl: ""
  signinUrl: ""
  responseHeaders: "Remote-User,Remote-Name,Remote-Groups,Remote-Email"
