{{- $kubeNs := .Values.secrets.backend.kubernetes.namespace | default (printf "%s-secrets" .Values.stack.name) }}
{{- if .Values.secrets.backend.infisical.projectSlug }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.stack.name }}
spec:
  provider:
    infisical:
      hostAPI: {{ .Values.secrets.backend.infisical.endpoint }}
      auth:
        universalAuthCredentials:
          clientId:
            name: universal-auth-credentials
            namespace: external-secrets
            key: clientId
          clientSecret:
            name: universal-auth-credentials
            namespace: external-secrets
            key: clientSecret
      secretsScope:
        projectSlug: {{ .Values.secrets.backend.infisical.projectSlug }}
        environmentSlug: {{ .Values.secrets.backend.infisical.environment }}
        secretsPath: {{ .Values.secrets.backend.infisical.secretsPath }}
{{- else }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.stack.name }}
spec:
  provider:
    kubernetes:
      remoteNamespace: {{ $kubeNs }}
      server:
        url: "https://kubernetes.default.svc"
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: kube-system
          key: ca.crt
      auth:
        serviceAccount:
          name: {{ .Values.stack.name }}-local-reader
          namespace: external-secrets
{{- end }}
