{{- $kubeNs := .Values.secrets.backend.kubernetes.namespace | default (printf "%s-secrets" .Values.stack.name) }}
{{- if not .Values.secrets.backend.infisical.projectSlug }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.stack.name }}-local-reader
  namespace: external-secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.stack.name }}-local-reader
  namespace: {{ $kubeNs }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.stack.name }}-local-reader
  namespace: {{ $kubeNs }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.stack.name }}-local-reader
subjects:
  - kind: ServiceAccount
    name: {{ .Values.stack.name }}-local-reader
    namespace: external-secrets
{{- end }}
